//! Ability definitions for class kits (slots 1–5).

use crate::ability_effects::{aura, AbilityEffect, AuraDef, DamageSchool};

#[derive(Debug, Clone)]
pub struct AbilityDef {
    pub id: &'static str,
    pub name: &'static str,
    pub damage: f32,
    pub cost: f32,
    pub cooldown: f32,
    pub range: f32,
    /// Seconds to finish a cast before the hit resolves. `0` = instant.
    pub cast_time: f32,
    /// Minimum player level required to know / use this ability.
    pub min_level: u32,
    /// Optional on-hit / ApplyAura id from the aura table.
    pub aura: Option<&'static str>,
    pub effect: AbilityEffect,
}

/// Resolve the aura applied when `ability_id` lands. Combat must not match on
/// ability id strings — this is the content-table lookup.
pub fn aura_for_ability(ability_id: &str) -> Option<&'static AuraDef> {
    ability(ability_id)?.aura.and_then(aura)
}

pub static ABILITIES: &[AbilityDef] = &[
    // —— Warrior ——
    AbilityDef {
        id: "heroic_strike",
        name: "Heroic Strike",
        damage: 28.0,
        cost: 15.0,
        cooldown: 3.0,
        range: 3.0,
        cast_time: 0.0,
        min_level: 1,
        aura: None,
        effect: AbilityEffect::WeaponDamage { coefficient: 1.0 },
    },
    AbilityDef {
        id: "cleave",
        name: "Cleave",
        damage: 22.0,
        cost: 20.0,
        cooldown: 4.0,
        range: 3.0,
        cast_time: 0.0,
        min_level: 3,
        aura: None,
        effect: AbilityEffect::AoeDamage {
            radius: 4.0,
            max_targets: 3,
        },
    },
    AbilityDef {
        id: "execute",
        name: "Execute",
        damage: 48.0,
        cost: 25.0,
        cooldown: 6.0,
        range: 3.0,
        cast_time: 0.0,
        min_level: 6,
        aura: None,
        effect: AbilityEffect::Execute {
            hp_pct: 0.2,
            coefficient: 1.75,
        },
    },
    AbilityDef {
        id: "taunt",
        name: "Taunt",
        damage: 0.0,
        cost: 0.0,
        cooldown: 8.0,
        range: 8.0,
        cast_time: 0.0,
        min_level: 1,
        aura: None,
        effect: AbilityEffect::Taunt { threat: 80.0 },
    },
    AbilityDef {
        id: "rend",
        name: "Rend",
        damage: 8.0,
        cost: 10.0,
        cooldown: 6.0,
        range: 3.0,
        cast_time: 0.0,
        min_level: 1,
        aura: Some("rend"),
        effect: AbilityEffect::ApplyAura,
    },
    // —— Paladin ——
    AbilityDef {
        id: "crusader_strike",
        name: "Crusader Strike",
        damage: 26.0,
        cost: 20.0,
        cooldown: 3.0,
        range: 3.0,
        cast_time: 0.0,
        min_level: 1,
        aura: None,
        effect: AbilityEffect::WeaponDamage { coefficient: 1.0 },
    },
    AbilityDef {
        id: "judgment",
        name: "Judgment",
        damage: 32.0,
        cost: 30.0,
        cooldown: 4.5,
        range: 12.0,
        cast_time: 0.0,
        min_level: 3,
        aura: None,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Holy,
        },
    },
    AbilityDef {
        id: "holy_shock",
        name: "Holy Shock",
        damage: 40.0,
        cost: 35.0,
        cooldown: 5.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 6,
        aura: None,
        effect: AbilityEffect::HealOrHarm { coefficient: 1.0 },
    },
    AbilityDef {
        id: "holy_light",
        name: "Holy Light",
        damage: 32.0,
        cost: 30.0,
        cooldown: 2.5,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        aura: None,
        effect: AbilityEffect::Heal { coefficient: 1.0 },
    },
    AbilityDef {
        id: "hammer_of_justice",
        name: "Hammer of Justice",
        damage: 12.0,
        cost: 20.0,
        cooldown: 8.0,
        range: 8.0,
        cast_time: 0.0,
        min_level: 3,
        aura: Some("hammer_of_justice"),
        effect: AbilityEffect::ApplyAura,
    },
    // —— Hunter ——
    AbilityDef {
        id: "arcane_shot",
        name: "Arcane Shot",
        damage: 24.0,
        cost: 25.0,
        cooldown: 2.5,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        aura: None,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Arcane,
        },
    },
    AbilityDef {
        id: "serpent_sting",
        name: "Serpent Sting",
        damage: 12.0,
        cost: 20.0,
        cooldown: 3.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 3,
        aura: Some("serpent_sting"),
        effect: AbilityEffect::ApplyAura,
    },
    AbilityDef {
        id: "aimed_shot",
        name: "Aimed Shot",
        damage: 42.0,
        cost: 35.0,
        cooldown: 5.0,
        range: 22.0,
        cast_time: 1.5,
        min_level: 6,
        aura: None,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Physical,
        },
    },
    AbilityDef {
        id: "concussive_shot",
        name: "Concussive Shot",
        damage: 10.0,
        cost: 20.0,
        cooldown: 8.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        aura: Some("chill"),
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Physical,
        },
    },
    AbilityDef {
        id: "multi_shot",
        name: "Multi-Shot",
        damage: 20.0,
        cost: 35.0,
        cooldown: 6.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 6,
        aura: None,
        effect: AbilityEffect::AoeDamage {
            radius: 6.0,
            max_targets: 3,
        },
    },
    // —— Rogue ——
    AbilityDef {
        id: "sinister_strike",
        name: "Sinister Strike",
        damage: 22.0,
        cost: 30.0,
        cooldown: 1.5,
        range: 3.0,
        cast_time: 0.0,
        min_level: 1,
        aura: None,
        effect: AbilityEffect::WeaponDamage { coefficient: 1.0 },
    },
    AbilityDef {
        id: "eviscerate",
        name: "Eviscerate",
        damage: 36.0,
        cost: 35.0,
        cooldown: 3.0,
        range: 3.0,
        cast_time: 0.0,
        min_level: 3,
        aura: None,
        effect: AbilityEffect::WeaponDamage { coefficient: 1.4 },
    },
    AbilityDef {
        id: "cheap_shot",
        name: "Cheap Shot",
        damage: 18.0,
        cost: 40.0,
        cooldown: 6.0,
        range: 3.0,
        cast_time: 0.0,
        min_level: 6,
        aura: Some("cheap_shot"),
        effect: AbilityEffect::WeaponDamage { coefficient: 1.0 },
    },
    AbilityDef {
        id: "kick",
        name: "Kick",
        damage: 8.0,
        cost: 25.0,
        cooldown: 6.0,
        range: 3.0,
        cast_time: 0.0,
        min_level: 1,
        aura: None,
        effect: AbilityEffect::Interrupt,
    },
    // —— Priest ——
    AbilityDef {
        id: "smite",
        name: "Smite",
        damage: 25.0,
        cost: 25.0,
        cooldown: 2.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        aura: None,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Holy,
        },
    },
    AbilityDef {
        id: "holy_fire",
        name: "Holy Fire",
        damage: 20.0,
        cost: 30.0,
        cooldown: 4.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 3,
        aura: Some("holy_fire"),
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Holy,
        },
    },
    AbilityDef {
        id: "mind_blast",
        name: "Mind Blast",
        damage: 38.0,
        cost: 40.0,
        cooldown: 5.0,
        range: 18.0,
        cast_time: 1.0,
        min_level: 6,
        aura: None,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Shadow,
        },
    },
    AbilityDef {
        id: "flash_heal",
        name: "Flash Heal",
        damage: 36.0,
        cost: 30.0,
        cooldown: 2.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        aura: None,
        effect: AbilityEffect::Heal { coefficient: 1.0 },
    },
    AbilityDef {
        id: "shadow_word_pain",
        name: "Shadow Word: Pain",
        damage: 10.0,
        cost: 25.0,
        cooldown: 4.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 3,
        aura: Some("shadow_word_pain"),
        effect: AbilityEffect::ApplyAura,
    },
    // —— Shaman ——
    AbilityDef {
        id: "lightning_bolt",
        name: "Lightning Bolt",
        damage: 27.0,
        cost: 30.0,
        cooldown: 2.5,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        aura: None,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Nature,
        },
    },
    AbilityDef {
        id: "earth_shock",
        name: "Earth Shock",
        damage: 24.0,
        cost: 25.0,
        cooldown: 3.0,
        range: 14.0,
        cast_time: 0.0,
        min_level: 3,
        aura: None,
        effect: AbilityEffect::Interrupt,
    },
    AbilityDef {
        id: "lava_burst",
        name: "Lava Burst",
        damage: 44.0,
        cost: 40.0,
        cooldown: 5.5,
        range: 18.0,
        cast_time: 1.2,
        min_level: 6,
        aura: Some("ignite"),
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Fire,
        },
    },
    AbilityDef {
        id: "healing_wave",
        name: "Healing Wave",
        damage: 34.0,
        cost: 30.0,
        cooldown: 2.5,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        aura: None,
        effect: AbilityEffect::Heal { coefficient: 1.0 },
    },
    AbilityDef {
        id: "flame_shock",
        name: "Flame Shock",
        damage: 14.0,
        cost: 25.0,
        cooldown: 5.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 3,
        aura: Some("flame_shock"),
        effect: AbilityEffect::ApplyAura,
    },
    // —— Mage ——
    AbilityDef {
        id: "fireball",
        name: "Fireball",
        damage: 30.0,
        cost: 35.0,
        cooldown: 2.5,
        range: 20.0,
        cast_time: 1.5,
        min_level: 1,
        aura: Some("ignite"),
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Fire,
        },
    },
    AbilityDef {
        id: "frostbolt",
        name: "Frostbolt",
        damage: 26.0,
        cost: 30.0,
        cooldown: 2.5,
        range: 20.0,
        cast_time: 1.0,
        min_level: 3,
        aura: Some("chill"),
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Frost,
        },
    },
    AbilityDef {
        id: "arcane_missiles",
        name: "Arcane Missiles",
        damage: 36.0,
        cost: 40.0,
        cooldown: 4.0,
        range: 20.0,
        cast_time: 0.0,
        min_level: 6,
        aura: None,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Arcane,
        },
    },
    AbilityDef {
        id: "frost_nova",
        name: "Frost Nova",
        damage: 16.0,
        cost: 30.0,
        cooldown: 8.0,
        range: 8.0,
        cast_time: 0.0,
        min_level: 3,
        aura: Some("chill"),
        effect: AbilityEffect::AoeDamage {
            radius: 8.0,
            max_targets: 5,
        },
    },
    AbilityDef {
        id: "counterspell",
        name: "Counterspell",
        damage: 6.0,
        cost: 20.0,
        cooldown: 8.0,
        range: 20.0,
        cast_time: 0.0,
        min_level: 6,
        aura: None,
        effect: AbilityEffect::Interrupt,
    },
    // —— Warlock ——
    AbilityDef {
        id: "shadow_bolt",
        name: "Shadow Bolt",
        damage: 28.0,
        cost: 30.0,
        cooldown: 2.5,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        aura: None,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Shadow,
        },
    },
    AbilityDef {
        id: "corruption",
        name: "Corruption",
        damage: 10.0,
        cost: 25.0,
        cooldown: 3.5,
        range: 18.0,
        cast_time: 0.0,
        min_level: 3,
        aura: Some("corruption"),
        effect: AbilityEffect::ApplyAura,
    },
    AbilityDef {
        id: "incinerate",
        name: "Incinerate",
        damage: 40.0,
        cost: 40.0,
        cooldown: 4.5,
        range: 18.0,
        cast_time: 1.2,
        min_level: 6,
        aura: Some("ignite"),
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Fire,
        },
    },
    AbilityDef {
        id: "immolate",
        name: "Immolate",
        damage: 12.0,
        cost: 25.0,
        cooldown: 4.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        aura: Some("immolate"),
        effect: AbilityEffect::ApplyAura,
    },
    // —— Druid ——
    AbilityDef {
        id: "wrath",
        name: "Wrath",
        damage: 26.0,
        cost: 25.0,
        cooldown: 2.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        aura: None,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Nature,
        },
    },
    AbilityDef {
        id: "moonfire",
        name: "Moonfire",
        damage: 14.0,
        cost: 25.0,
        cooldown: 3.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 3,
        aura: Some("moonfire"),
        effect: AbilityEffect::ApplyAura,
    },
    AbilityDef {
        id: "starfire",
        name: "Starfire",
        damage: 42.0,
        cost: 40.0,
        cooldown: 5.0,
        range: 20.0,
        cast_time: 1.5,
        min_level: 6,
        aura: None,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Arcane,
        },
    },
    AbilityDef {
        id: "rejuvenation",
        name: "Rejuvenation",
        damage: 12.0,
        cost: 20.0,
        cooldown: 3.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        aura: Some("rejuvenation"),
        effect: AbilityEffect::Heal { coefficient: 0.4 },
    },
    AbilityDef {
        id: "healing_touch",
        name: "Healing Touch",
        damage: 38.0,
        cost: 35.0,
        cooldown: 2.5,
        range: 18.0,
        cast_time: 0.0,
        min_level: 6,
        aura: None,
        effect: AbilityEffect::Heal { coefficient: 1.0 },
    },
];

pub fn ability(id: &str) -> Option<&'static AbilityDef> {
    ABILITIES.iter().find(|a| a.id == id)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_class_auras_resolve_from_ability_table() {
        assert_eq!(aura_for_ability("rend").unwrap().id, "rend");
        assert_eq!(aura_for_ability("fireball").unwrap().id, "ignite");
        assert_eq!(
            aura_for_ability("serpent_sting").unwrap().id,
            "serpent_sting"
        );
        assert_eq!(aura_for_ability("frostbolt").unwrap().id, "chill");
        assert!(aura_for_ability("cheap_shot").unwrap().stun);
        assert!(aura_for_ability("heroic_strike").is_none());
        assert!(aura_for_ability("flash_heal").is_none());
        assert!(aura_for_ability("taunt").is_none());
    }

    #[test]
    fn execute_and_holy_shock_use_special_effects() {
        assert!(matches!(
            ability("execute").unwrap().effect,
            AbilityEffect::Execute { hp_pct, .. } if (hp_pct - 0.2).abs() < f32::EPSILON
        ));
        assert!(matches!(
            ability("holy_shock").unwrap().effect,
            AbilityEffect::HealOrHarm { .. }
        ));
    }
}
