//! Ability definitions for class kits (slots 1–5).

use crate::ability_effects::{AbilityEffect, DamageSchool};

#[derive(Debug, Clone)]
pub struct AbilityDef {
    pub id: &'static str,
    pub name: &'static str,
    pub damage: f32,
    pub cost: f32,
    pub cooldown: f32,
    pub range: f32,
    /// Seconds to finish a cast before the hit resolves. `0` = instant.
    pub cast_time: f32,
    /// Minimum player level required to know / use this ability.
    pub min_level: u32,
    pub effect: AbilityEffect,
}

pub static ABILITIES: &[AbilityDef] = &[
    // —— Warrior ——
    AbilityDef {
        id: "heroic_strike",
        name: "Heroic Strike",
        damage: 28.0,
        cost: 15.0,
        cooldown: 3.0,
        range: 3.0,
        cast_time: 0.0,
        min_level: 1,
        effect: AbilityEffect::WeaponDamage { coefficient: 1.0 },
    },
    AbilityDef {
        id: "cleave",
        name: "Cleave",
        damage: 22.0,
        cost: 20.0,
        cooldown: 4.0,
        range: 3.0,
        cast_time: 0.0,
        min_level: 3,
        effect: AbilityEffect::AoeDamage {
            radius: 4.0,
            max_targets: 3,
        },
    },
    AbilityDef {
        id: "execute",
        name: "Execute",
        damage: 48.0,
        cost: 25.0,
        cooldown: 6.0,
        range: 3.0,
        cast_time: 0.0,
        min_level: 6,
        effect: AbilityEffect::WeaponDamage { coefficient: 1.0 },
    },
    // —— Paladin ——
    AbilityDef {
        id: "crusader_strike",
        name: "Crusader Strike",
        damage: 26.0,
        cost: 20.0,
        cooldown: 3.0,
        range: 3.0,
        cast_time: 0.0,
        min_level: 1,
        effect: AbilityEffect::WeaponDamage { coefficient: 1.0 },
    },
    AbilityDef {
        id: "judgment",
        name: "Judgment",
        damage: 32.0,
        cost: 30.0,
        cooldown: 4.5,
        range: 12.0,
        cast_time: 0.0,
        min_level: 3,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Holy,
        },
    },
    AbilityDef {
        id: "holy_shock",
        name: "Holy Shock",
        damage: 40.0,
        cost: 35.0,
        cooldown: 5.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 6,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Holy,
        },
    },
    // —— Hunter ——
    AbilityDef {
        id: "arcane_shot",
        name: "Arcane Shot",
        damage: 24.0,
        cost: 25.0,
        cooldown: 2.5,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Arcane,
        },
    },
    AbilityDef {
        id: "serpent_sting",
        name: "Serpent Sting",
        damage: 12.0,
        cost: 20.0,
        cooldown: 3.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 3,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Nature,
        },
    },
    AbilityDef {
        id: "aimed_shot",
        name: "Aimed Shot",
        damage: 42.0,
        cost: 35.0,
        cooldown: 5.0,
        range: 22.0,
        cast_time: 1.5,
        min_level: 6,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Physical,
        },
    },
    // —— Rogue ——
    AbilityDef {
        id: "sinister_strike",
        name: "Sinister Strike",
        damage: 22.0,
        cost: 30.0,
        cooldown: 1.5,
        range: 3.0,
        cast_time: 0.0,
        min_level: 1,
        effect: AbilityEffect::WeaponDamage { coefficient: 1.0 },
    },
    AbilityDef {
        id: "eviscerate",
        name: "Eviscerate",
        damage: 36.0,
        cost: 35.0,
        cooldown: 3.0,
        range: 3.0,
        cast_time: 0.0,
        min_level: 3,
        effect: AbilityEffect::WeaponDamage { coefficient: 1.0 },
    },
    AbilityDef {
        id: "cheap_shot",
        name: "Cheap Shot",
        damage: 30.0,
        cost: 40.0,
        cooldown: 6.0,
        range: 3.0,
        cast_time: 0.0,
        min_level: 6,
        effect: AbilityEffect::WeaponDamage { coefficient: 1.0 },
    },
    // —— Priest ——
    AbilityDef {
        id: "smite",
        name: "Smite",
        damage: 25.0,
        cost: 25.0,
        cooldown: 2.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Holy,
        },
    },
    AbilityDef {
        id: "holy_fire",
        name: "Holy Fire",
        damage: 20.0,
        cost: 30.0,
        cooldown: 4.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 3,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Holy,
        },
    },
    AbilityDef {
        id: "mind_blast",
        name: "Mind Blast",
        damage: 38.0,
        cost: 40.0,
        cooldown: 5.0,
        range: 18.0,
        cast_time: 1.0,
        min_level: 6,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Shadow,
        },
    },
    // —— Shaman ——
    AbilityDef {
        id: "lightning_bolt",
        name: "Lightning Bolt",
        damage: 27.0,
        cost: 30.0,
        cooldown: 2.5,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Nature,
        },
    },
    AbilityDef {
        id: "earth_shock",
        name: "Earth Shock",
        damage: 24.0,
        cost: 25.0,
        cooldown: 3.0,
        range: 14.0,
        cast_time: 0.0,
        min_level: 3,
        effect: AbilityEffect::Interrupt,
    },
    AbilityDef {
        id: "lava_burst",
        name: "Lava Burst",
        damage: 44.0,
        cost: 40.0,
        cooldown: 5.5,
        range: 18.0,
        cast_time: 1.2,
        min_level: 6,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Fire,
        },
    },
    // —— Mage ——
    AbilityDef {
        id: "fireball",
        name: "Fireball",
        damage: 30.0,
        cost: 35.0,
        cooldown: 2.5,
        range: 20.0,
        cast_time: 1.5,
        min_level: 1,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Fire,
        },
    },
    AbilityDef {
        id: "frostbolt",
        name: "Frostbolt",
        damage: 26.0,
        cost: 30.0,
        cooldown: 2.5,
        range: 20.0,
        cast_time: 1.0,
        min_level: 3,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Frost,
        },
    },
    AbilityDef {
        id: "arcane_missiles",
        name: "Arcane Missiles",
        damage: 36.0,
        cost: 40.0,
        cooldown: 4.0,
        range: 20.0,
        cast_time: 0.0,
        min_level: 6,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Arcane,
        },
    },
    // —— Warlock ——
    AbilityDef {
        id: "shadow_bolt",
        name: "Shadow Bolt",
        damage: 28.0,
        cost: 30.0,
        cooldown: 2.5,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Shadow,
        },
    },
    AbilityDef {
        id: "corruption",
        name: "Corruption",
        damage: 10.0,
        cost: 25.0,
        cooldown: 3.5,
        range: 18.0,
        cast_time: 0.0,
        min_level: 3,
        effect: AbilityEffect::ApplyAura,
    },
    AbilityDef {
        id: "incinerate",
        name: "Incinerate",
        damage: 40.0,
        cost: 40.0,
        cooldown: 4.5,
        range: 18.0,
        cast_time: 1.2,
        min_level: 6,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Fire,
        },
    },
    // —— Druid ——
    AbilityDef {
        id: "wrath",
        name: "Wrath",
        damage: 26.0,
        cost: 25.0,
        cooldown: 2.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Nature,
        },
    },
    AbilityDef {
        id: "moonfire",
        name: "Moonfire",
        damage: 14.0,
        cost: 25.0,
        cooldown: 3.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 3,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Arcane,
        },
    },
    AbilityDef {
        id: "starfire",
        name: "Starfire",
        damage: 42.0,
        cost: 40.0,
        cooldown: 5.0,
        range: 20.0,
        cast_time: 1.5,
        min_level: 6,
        effect: AbilityEffect::SpellDamage {
            school: DamageSchool::Arcane,
        },
    },
    AbilityDef {
        id: "flash_heal",
        name: "Flash Heal",
        damage: 36.0,
        cost: 30.0,
        cooldown: 2.0,
        range: 18.0,
        cast_time: 0.0,
        min_level: 1,
        effect: AbilityEffect::Heal { coefficient: 1.0 },
    },
    AbilityDef {
        id: "taunt",
        name: "Taunt",
        damage: 0.0,
        cost: 0.0,
        cooldown: 8.0,
        range: 8.0,
        cast_time: 0.0,
        min_level: 1,
        effect: AbilityEffect::Taunt { threat: 80.0 },
    },
];

pub fn ability(id: &str) -> Option<&'static AbilityDef> {
    ABILITIES.iter().find(|a| a.id == id)
}
