//! World gather-node placements for gathering professions.

#[derive(Debug, Clone, Copy)]
pub struct GatherNodeDef {
    pub id: &'static str,
    pub name: &'static str,
    /// Profession required to harvest (`herbalism`, …).
    pub profession_id: &'static str,
    pub zone_id: &'static str,
    pub x: f32,
    pub z: f32,
    /// Item granted on a successful gather (base quality).
    pub item_id: &'static str,
    pub count: u32,
    pub skill_req: u32,
    pub tool_item_id: &'static str,
    pub tier: u8,
    pub respawn_seconds: u32,
    pub fine_item_id: Option<&'static str>,
    pub bonus_item_id: Option<&'static str>,
}

/// Conceptual placements around Eastbrook Vale (near meadow / brook edges).
pub static GATHER_NODES: &[GatherNodeDef] = &[
    GatherNodeDef {
        id: "eastbrook_meadow_silverleaf",
        name: "Silverleaf Patch",
        profession_id: "herbalism",
        zone_id: "eastbrook",
        x: 14.0,
        z: 10.0,
        item_id: "silverleaf",
        count: 1,
        skill_req: 0,
        tool_item_id: "copper_sickle",
        tier: 1,
        respawn_seconds: 60,
        fine_item_id: Some("fine_silverleaf"),
        bonus_item_id: None,
    },
    GatherNodeDef {
        id: "eastbrook_brook_peacebloom",
        name: "Peacebloom Clump",
        profession_id: "herbalism",
        zone_id: "eastbrook",
        x: -10.0,
        z: 12.0,
        item_id: "peacebloom",
        count: 1,
        skill_req: 0,
        tool_item_id: "copper_sickle",
        tier: 1,
        respawn_seconds: 60,
        fine_item_id: None,
        bonus_item_id: None,
    },
    GatherNodeDef {
        id: "eastbrook_north_briar",
        name: "Briarroot Thicket",
        profession_id: "herbalism",
        zone_id: "eastbrook",
        x: -6.0,
        z: -18.0,
        item_id: "briarroot",
        count: 1,
        skill_req: 0,
        tool_item_id: "copper_sickle",
        tier: 1,
        respawn_seconds: 60,
        fine_item_id: None,
        bonus_item_id: None,
    },
    GatherNodeDef {
        id: "eastbrook_earthroot",
        name: "Earthroot Cluster",
        profession_id: "herbalism",
        zone_id: "eastbrook",
        x: 40.0,
        z: 8.0,
        item_id: "earthroot",
        count: 1,
        skill_req: 0,
        tool_item_id: "copper_sickle",
        tier: 1,
        respawn_seconds: 60,
        fine_item_id: Some("fine_earthroot"),
        bonus_item_id: None,
    },
    GatherNodeDef {
        id: "eastbrook_south_copper",
        name: "Copper Vein",
        profession_id: "mining",
        zone_id: "eastbrook",
        x: 10.0,
        z: -14.0,
        item_id: "copper_ore",
        count: 1,
        skill_req: 0,
        tool_item_id: "copper_pick",
        tier: 1,
        respawn_seconds: 60,
        fine_item_id: Some("fine_copper_ore"),
        bonus_item_id: Some("coarse_stone"),
    },
    GatherNodeDef {
        id: "eastbrook_ridge_copper",
        name: "Copper Vein",
        profession_id: "mining",
        zone_id: "eastbrook",
        x: -18.0,
        z: 6.0,
        item_id: "copper_ore",
        count: 1,
        skill_req: 0,
        tool_item_id: "copper_pick",
        tier: 1,
        respawn_seconds: 60,
        fine_item_id: Some("fine_copper_ore"),
        bonus_item_id: Some("coarse_stone"),
    },
    GatherNodeDef {
        id: "eastfen_fenbridge_copper",
        name: "Copper Vein",
        profession_id: "mining",
        zone_id: "eastfen",
        x: 16.0,
        z: 298.0,
        item_id: "copper_ore",
        count: 1,
        skill_req: 0,
        tool_item_id: "copper_pick",
        tier: 1,
        respawn_seconds: 60,
        fine_item_id: Some("fine_copper_ore"),
        bonus_item_id: Some("coarse_stone"),
    },
];

pub fn gather_node(id: &str) -> Option<&'static GatherNodeDef> {
    GATHER_NODES.iter().find(|n| n.id == id)
}

/// All gather nodes placed in `zone_id`.
pub fn gather_nodes_for_zone(zone_id: &str) -> impl Iterator<Item = &'static GatherNodeDef> + '_ {
    GATHER_NODES.iter().filter(move |n| n.zone_id == zone_id)
}
