//! Zone 2 (Eastfen Marsh) item definitions.

use crate::items::{ItemDef, ItemEquipSlot, ItemKind};

pub static ZONE2_ITEMS: &[ItemDef] = &[
    ItemDef {
        id: "fen_silk",
        name: "Fen Silk",
        kind: ItemKind::Quest,
        stack_size: 20,
        vendor_buy: 0,
        vendor_sell: 2,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 0.0,
    },
    ItemDef {
        id: "toad_bile",
        name: "Toad Bile",
        kind: ItemKind::Quest,
        stack_size: 20,
        vendor_buy: 0,
        vendor_sell: 2,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 0.0,
    },
    ItemDef {
        id: "wisp_ember",
        name: "Wisp Ember",
        kind: ItemKind::Quest,
        stack_size: 20,
        vendor_buy: 0,
        vendor_sell: 3,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 0.0,
    },
    ItemDef {
        id: "fen_tonic",
        name: "Fen Tonic",
        kind: ItemKind::Consumable,
        stack_size: 20,
        vendor_buy: 18,
        vendor_sell: 4,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 120.0,
    },
    ItemDef {
        id: "marsh_wraps",
        name: "Marsh Wraps",
        kind: ItemKind::Armor,
        stack_size: 1,
        vendor_buy: 0,
        vendor_sell: 14,
        attack_power: 0.0,
        armor: 16.0,
        equip_slot: Some(ItemEquipSlot::Chest),
        level_req: 3,
        heal_hp: 0.0,
    },
    ItemDef {
        id: "reedwalk_boots",
        name: "Reedwalk Boots",
        kind: ItemKind::Armor,
        stack_size: 1,
        vendor_buy: 0,
        vendor_sell: 12,
        attack_power: 0.0,
        armor: 10.0,
        equip_slot: Some(ItemEquipSlot::Feet),
        level_req: 3,
        heal_hp: 0.0,
    },
    ItemDef {
        id: "leech_ichor",
        name: "Leech Ichor",
        kind: ItemKind::Quest,
        stack_size: 20,
        vendor_buy: 0,
        vendor_sell: 4,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 0.0,
    },
    ItemDef {
        id: "rotcap_spore",
        name: "Rotcap Spore",
        kind: ItemKind::Quest,
        stack_size: 20,
        vendor_buy: 0,
        vendor_sell: 5,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 0.0,
    },
    ItemDef {
        id: "terror_scale",
        name: "Mire Terror Scale",
        kind: ItemKind::Quest,
        stack_size: 5,
        vendor_buy: 0,
        vendor_sell: 25,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 0.0,
    },
    ItemDef {
        id: "deepfen_draught",
        name: "Deepfen Draught",
        kind: ItemKind::Consumable,
        stack_size: 20,
        vendor_buy: 30,
        vendor_sell: 7,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 180.0,
    },
    ItemDef {
        id: "mireguard_hood",
        name: "Mireguard Hood",
        kind: ItemKind::Armor,
        stack_size: 1,
        vendor_buy: 0,
        vendor_sell: 28,
        attack_power: 0.0,
        armor: 18.0,
        equip_slot: Some(ItemEquipSlot::Head),
        level_req: 5,
        heal_hp: 0.0,
    },
];
