//! Zone 2 (Eastfen Marsh) item definitions.

use crate::items::{ArmorClass, ItemDef, ItemEquipSlot, ItemKind};

pub static ZONE2_ITEMS: &[ItemDef] = &[
    ItemDef {
        id: "fen_silk",
        name: "Fen Silk",
        kind: ItemKind::Quest,
        stack_size: 20,
        max_durability: 0,
        vendor_buy: 0,
        vendor_sell: 2,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 0.0,
        armor_class: None,
        weapon_style: None,
        allowed_classes: &[],
        stamina: 0.0,
        spell_power: 0.0,
        quality: crate::items::ItemQuality::Common,
        enchant_id: None,
    },
    ItemDef {
        id: "toad_bile",
        name: "Toad Bile",
        kind: ItemKind::Quest,
        stack_size: 20,
        max_durability: 0,
        vendor_buy: 0,
        vendor_sell: 2,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 0.0,
        armor_class: None,
        weapon_style: None,
        allowed_classes: &[],
        stamina: 0.0,
        spell_power: 0.0,
        quality: crate::items::ItemQuality::Common,
        enchant_id: None,
    },
    ItemDef {
        id: "wisp_ember",
        name: "Wisp Ember",
        kind: ItemKind::Quest,
        stack_size: 20,
        max_durability: 0,
        vendor_buy: 0,
        vendor_sell: 3,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 0.0,
        armor_class: None,
        weapon_style: None,
        allowed_classes: &[],
        stamina: 0.0,
        spell_power: 0.0,
        quality: crate::items::ItemQuality::Common,
        enchant_id: None,
    },
    ItemDef {
        id: "fen_tonic",
        name: "Fen Tonic",
        kind: ItemKind::Consumable,
        stack_size: 20,
        max_durability: 0,
        vendor_buy: 18,
        vendor_sell: 4,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 120.0,
        armor_class: None,
        weapon_style: None,
        allowed_classes: &[],
        stamina: 0.0,
        spell_power: 0.0,
        quality: crate::items::ItemQuality::Common,
        enchant_id: None,
    },
    ItemDef {
        id: "marsh_wraps",
        name: "Marsh Wraps",
        kind: ItemKind::Armor,
        stack_size: 1,
        max_durability: 30,
        vendor_buy: 0,
        vendor_sell: 14,
        attack_power: 0.0,
        armor: 16.0,
        equip_slot: Some(ItemEquipSlot::Chest),
        level_req: 3,
        heal_hp: 0.0,
        armor_class: Some(ArmorClass::Leather),
        weapon_style: None,
        allowed_classes: &[],
        stamina: 0.0,
        spell_power: 0.0,
        quality: crate::items::ItemQuality::Uncommon,
        enchant_id: None,
    },
    ItemDef {
        id: "reedwalk_boots",
        name: "Reedwalk Boots",
        kind: ItemKind::Armor,
        stack_size: 1,
        max_durability: 30,
        vendor_buy: 0,
        vendor_sell: 12,
        attack_power: 0.0,
        armor: 10.0,
        equip_slot: Some(ItemEquipSlot::Feet),
        level_req: 3,
        heal_hp: 0.0,
        armor_class: Some(ArmorClass::Leather),
        weapon_style: None,
        allowed_classes: &[],
        stamina: 0.0,
        spell_power: 0.0,
        quality: crate::items::ItemQuality::Uncommon,
        enchant_id: None,
    },
    ItemDef {
        id: "leech_ichor",
        name: "Leech Ichor",
        kind: ItemKind::Quest,
        stack_size: 20,
        max_durability: 0,
        vendor_buy: 0,
        vendor_sell: 4,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 0.0,
        armor_class: None,
        weapon_style: None,
        allowed_classes: &[],
        stamina: 0.0,
        spell_power: 0.0,
        quality: crate::items::ItemQuality::Common,
        enchant_id: None,
    },
    ItemDef {
        id: "rotcap_spore",
        name: "Rotcap Spore",
        kind: ItemKind::Quest,
        stack_size: 20,
        max_durability: 0,
        vendor_buy: 0,
        vendor_sell: 5,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 0.0,
        armor_class: None,
        weapon_style: None,
        allowed_classes: &[],
        stamina: 0.0,
        spell_power: 0.0,
        quality: crate::items::ItemQuality::Common,
        enchant_id: None,
    },
    ItemDef {
        id: "terror_scale",
        name: "Mire Terror Scale",
        kind: ItemKind::Quest,
        stack_size: 5,
        max_durability: 0,
        vendor_buy: 0,
        vendor_sell: 25,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 0.0,
        armor_class: None,
        weapon_style: None,
        allowed_classes: &[],
        stamina: 0.0,
        spell_power: 0.0,
        quality: crate::items::ItemQuality::Common,
        enchant_id: None,
    },
    ItemDef {
        id: "deepfen_draught",
        name: "Deepfen Draught",
        kind: ItemKind::Consumable,
        stack_size: 20,
        max_durability: 0,
        vendor_buy: 30,
        vendor_sell: 7,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 180.0,
        armor_class: None,
        weapon_style: None,
        allowed_classes: &[],
        stamina: 0.0,
        spell_power: 0.0,
        quality: crate::items::ItemQuality::Common,
        enchant_id: None,
    },
    ItemDef {
        id: "mireguard_hood",
        name: "Mireguard Hood",
        kind: ItemKind::Armor,
        stack_size: 1,
        max_durability: 30,
        vendor_buy: 0,
        vendor_sell: 28,
        attack_power: 0.0,
        armor: 18.0,
        equip_slot: Some(ItemEquipSlot::Head),
        level_req: 5,
        heal_hp: 0.0,
        armor_class: Some(ArmorClass::Leather),
        weapon_style: None,
        allowed_classes: &[],
        stamina: 0.0,
        spell_power: 0.0,
        quality: crate::items::ItemQuality::Uncommon,
        enchant_id: None,
    },
    ItemDef {
        id: "hag_claw",
        name: "Hag Claw",
        kind: ItemKind::Junk,
        stack_size: 20,
        max_durability: 0,
        vendor_buy: 0,
        vendor_sell: 8,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: None,
        level_req: 1,
        heal_hp: 0.0,
        armor_class: None,
        weapon_style: None,
        allowed_classes: &[],
        stamina: 0.0,
        spell_power: 0.0,
        quality: crate::items::ItemQuality::Common,
        enchant_id: None,
    },
    ItemDef {
        id: "fen_staff",
        name: "Fen Staff",
        kind: ItemKind::Weapon,
        stack_size: 1,
        max_durability: 40,
        vendor_buy: 0,
        vendor_sell: 22,
        attack_power: 9.0,
        armor: 0.0,
        equip_slot: Some(ItemEquipSlot::MainHand),
        level_req: 4,
        heal_hp: 0.0,
        armor_class: None,
        weapon_style: Some(crate::items::WeaponStyle::TwoHand),
        allowed_classes: &[
            crate::PlayerClass::Priest,
            crate::PlayerClass::Mage,
            crate::PlayerClass::Warlock,
            crate::PlayerClass::Druid,
        ],
        stamina: 0.0,
        spell_power: 6.0,
        quality: crate::items::ItemQuality::Rare,
        enchant_id: None,
    },
    ItemDef {
        id: "hag_focus",
        name: "Hag Focus",
        kind: ItemKind::Armor,
        stack_size: 1,
        max_durability: 0,
        vendor_buy: 0,
        vendor_sell: 30,
        attack_power: 0.0,
        armor: 0.0,
        equip_slot: Some(ItemEquipSlot::Neck),
        level_req: 5,
        heal_hp: 0.0,
        armor_class: None,
        weapon_style: None,
        allowed_classes: &[],
        stamina: 2.0,
        spell_power: 8.0,
        quality: crate::items::ItemQuality::Rare,
        enchant_id: None,
    },
];
